# Introduction to Pandas
---


Pandas is an open-source easy-to-use python library for data manipulation and analysis.

DataFrame is a 2-dimensional labeled data structure with columns of potentially different types. You can think of it like a spreadsheet or SQL table, or a dictionary of Series objects.

#Series : First main data type in Pandas

In [1]:
import pandas as pd
labels =['a','b','c']
my_data=[10,20,30]

d={'a':10,'b':10,'c':30}

In [2]:
pd.Series(d)

a    10
b    10
c    30
dtype: int64

#DataFrame

In [3]:
import numpy as np

x=np.random.randint(100,size=(5,4)) 
print("Numpy Array:")
x

Numpy Array:

array([[71, 71, 76, 25],
       [26, 16, 72, 94],
       [90, 83, 10, 15],
       [ 3,  2,  6, 72],
       [60, 13, 46, 46]])

In [4]:
import pandas as pd
df = pd.DataFrame(x)
print("Pandas DataFrame:")
df

Pandas DataFrame:

    0   1   2   3
0  71  71  76  25
1  26  16  72  94
2  90  83  10  15
3   3   2   6  72
4  60  13  46  46

In [5]:
df = pd.DataFrame(x,['x','b','c','d','e'],['W','X','Y','Z'])
print("Pandas DataFrame with custom indexing:")
df

Pandas DataFrame with custom indexing:

    W   X   Y   Z
x  71  71  76  25
b  26  16  72  94
c  90  83  10  15
d   3   2   6  72
e  60  13  46  46

In [6]:
df['X']

x    71
b    16
c    83
d     2
e    13
Name: X, dtype: int64

In [7]:
#ENTERING ANATHER COLUMN IN A DATAFRAME
df['new_col']=[1,2,3,4,5]
df

    W   X   Y   Z  new_col
x  71  71  76  25        1
b  26  16  72  94        2
c  90  83  10  15        3
d   3   2   6  72        4
e  60  13  46  46        5

In [8]:
#how delete column in dataframe:
df.drop('Y',axis=1,inplace=True)
print(df)

    W   X   Z  new_col
x  71  71  25        1
b  26  16  94        2
c  90  83  15        3
d   3   2  72        4
e  60  13  46        5

In [9]:
#how delete column in dataframe:
df.drop('c',axis=0,inplace=True)
print(df)

    W   X   Z  new_col
x  71  71  25        1
b  26  16  94        2
d   3   2  72        4
e  60  13  46        5

#Importing pandas library and reading a CSV file into a dataframe.

In [10]:
 df = pd.read_csv('/kaggle/input/sales-dataset-cse422csv/Sales Data (CSE422_ Pandas) - sales.csv',index_col='month')
 df.head()

       eggs  salt  spam
month
Jan      47  12.0    17
Feb     110  50.0    31
Mar     221  89.0    72
Apr      77  87.0    20
May     132   NaN    52

# Indexing DataFrames

## Indexing using square brackets

In [11]:
df = pd.read_csv('/kaggle/input/sales-dataset-cse422csv/Sales Data (CSE422_ Pandas) - sales.csv',index_col='month')
df.head()

       eggs  salt  spam
month
Jan      47  12.0    17
Feb     110  50.0    31
Mar     221  89.0    72
Apr      77  87.0    20
May     132   NaN    52

In [12]:
 df['eggs']['Mar'] # df[column]['rows']
 type(df)

pandas.core.frame.DataFrame

In [13]:
df.eggs['Apr']

77

Using column atribute and row index/label

In [14]:
df.salt['Apr']

87.0

Selecting only some columns

In [15]:
df_new = df[['salt','spam']]
df_new

       salt  spam
month
Jan    12.0    17
Feb    50.0    31
Mar    89.0    72
Apr    87.0    20
May     NaN    52
Jun    60.0    55

Selecting a column (i.e., Series)

In [16]:
 df['eggs']

month
Jan     47
Feb    110
Mar    221
Apr     77
May    132
Jun    205
Name: eggs, dtype: int64

In [17]:
#printing type of the column selected
type(df['eggs'])

pandas.core.series.Series

Slicing and indexing a Series

In [18]:
#selecting part of a series
df['eggs'][1:4]

month
Feb    110
Mar    221
Apr     77
Name: eggs, dtype: int64

In [19]:
df['eggs'][4]

132

# Slicing DataFrames

Using the .loc accessor
* Access a group of rows and columns by label(s) or a boolean array.

A series is a 1D-array that can store any data type

* LOC is not based on index. The stop limit is **not** exclusive
* ILOC is based on index. The stop limit is exclusive

In [20]:
#we can access row by 2 ways:
# 1. location based selection .loc('rowname')
# 2. numerical based selection  iloc(rowindex)
df2 = pd.DataFrame(x,['x','b','c','d','e'],['W','X','Y','Z'])
df2.loc[:,'X']

x    71
b    16
c    83
d     2
e    13
Name: X, dtype: int64

In [21]:
df

       eggs  salt  spam
month
Jan      47  12.0    17
Feb     110  50.0    31
Mar     221  89.0    72
Apr      77  87.0    20
May     132   NaN    52
Jun     205  60.0    55

In [22]:
df.loc['Feb':'Mar','eggs':'salt']

       eggs  salt
month
Feb     110  50.0
Mar     221  89.0

In [23]:
df.loc['Feb',:]   #df.loc[rows,column]

eggs    110.0
salt     50.0
spam     31.0
Name: Feb, dtype: float64

In [24]:
 df.loc['Jan': 'Mar', ['eggs','spam']]

       eggs  spam
month
Jan      47    17
Feb     110    31
Mar     221    72

In [25]:
df.loc[:, ['eggs','salt']]   # All rows, some columns

       eggs  salt
month
Jan      47  12.0
Feb     110  50.0
Mar     221  89.0
Apr      77  87.0
May     132   NaN
Jun     205  60.0

In [26]:
 df.loc['Jan':'Apr',:]  # Some rows, all columns

       eggs  salt  spam
month
Jan      47  12.0    17
Feb     110  50.0    31
Mar     221  89.0    72
Apr      77  87.0    20

In [27]:
df.loc['Mar':'May', 'salt':'spam']

       salt  spam
month
Mar    89.0    72
Apr    87.0    20
May     NaN    52

Using the .iloc accessor
* Purely integer-location based indexing for selection by position.

In [28]:
df

       eggs  salt  spam
month
Jan      47  12.0    17
Feb     110  50.0    31
Mar     221  89.0    72
Apr      77  87.0    20
May     132   NaN    52
Jun     205  60.0    55

In [29]:
df.iloc[2]  #indexwise
df.iloc[2,2]

72

In [30]:
 df.iloc[2:4, 2]

month
Mar    72
Apr    20
Name: spam, dtype: int64

In [31]:
 df

       eggs  salt  spam
month
Jan      47  12.0    17
Feb     110  50.0    31
Mar     221  89.0    72
Apr      77  87.0    20
May     132   NaN    52
Jun     205  60.0    55

In [32]:
df.iloc[2:5, 1:] # A block from middle of the DataFrame

       salt  spam
month
Mar    89.0    72
Apr    87.0    20
May     NaN    52

Using lists rather than slices (1)

In [33]:
df.loc['Jan':'May', ['eggs','salt']]

       eggs  salt
month
Jan      47  12.0
Feb     110  50.0
Mar     221  89.0
Apr      77  87.0
May     132   NaN

Using lists rather than slices (2)

In [34]:
df.iloc[[0,4,5], 0:2]

       eggs  salt
month
Jan      47  12.0
May     132   NaN
Jun     205  60.0

Series versus 1-column DataFrame

In [35]:
 df['eggs']

month
Jan     47
Feb    110
Mar    221
Apr     77
May    132
Jun    205
Name: eggs, dtype: int64

In [36]:
type(df['eggs'])

pandas.core.series.Series

In [37]:
df[['eggs']]

       eggs
month
Jan      47
Feb     110
Mar     221
Apr      77
May     132
Jun     205

In [38]:
type(df[['eggs']])

pandas.core.frame.DataFrame

#Filtering DataFrames

Creating a Boolean Series

In [39]:
df

       eggs  salt  spam
month
Jan      47  12.0    17
Feb     110  50.0    31
Mar     221  89.0    72
Apr      77  87.0    20
May     132   NaN    52
Jun     205  60.0    55

In [40]:
df['salt'] > 60

month
Jan    False
Feb    False
Mar     True
Apr     True
May    False
Jun    False
Name: salt, dtype: bool

Filtering with a Boolean Series

In [41]:
df.salt > 60

month
Jan    False
Feb    False
Mar     True
Apr     True
May    False
Jun    False
Name: salt, dtype: bool

In [42]:
a = df.salt > 60

In [43]:
type(a) #this is a series

pandas.core.series.Series

In [44]:
df[a]

       eggs  salt  spam
month
Mar     221  89.0    72
Apr      77  87.0    20

In [45]:
df[df.salt>60]

       eggs  salt  spam
month
Mar     221  89.0    72
Apr      77  87.0    20

Combining filters

In [46]:
(df.salt >= 50) & (df.eggs < 200)

month
Jan    False
Feb     True
Mar    False
Apr     True
May    False
Jun    False
dtype: bool

In [47]:
 df[(df.salt >= 50) & (df.eggs < 200)] # Both conditions

       eggs  salt  spam
month
Feb     110  50.0    31
Apr      77  87.0    20

In [48]:
(df.salt >= 50) | (df.eggs < 200)

month
Jan    True
Feb    True
Mar    True
Apr    True
May    True
Jun    True
dtype: bool

In [49]:
 df[(df.salt >= 50) | (df.eggs < 200)] # Either condition

       eggs  salt  spam
month
Jan      47  12.0    17
Feb     110  50.0    31
Mar     221  89.0    72
Apr      77  87.0    20
May     132   NaN    52
Jun     205  60.0    55

#DataFrame Append

In [50]:
df2 = df.copy()
df2

       eggs  salt  spam
month
Jan      47  12.0    17
Feb     110  50.0    31
Mar     221  89.0    72
Apr      77  87.0    20
May     132   NaN    52
Jun     205  60.0    55

In [51]:
 df2['bacon']=[0,0,60,0,90,100]
 df2

       eggs  salt  spam  bacon
month
Jan      47  12.0    17      0
Feb     110  50.0    31      0
Mar     221  89.0    72     60
Apr      77  87.0    20      0
May     132   NaN    52     90
Jun     205  60.0    55    100

In [52]:
df3=df2.copy()
df3

       eggs  salt  spam  bacon
month
Jan      47  12.0    17      0
Feb     110  50.0    31      0
Mar     221  89.0    72     60
Apr      77  87.0    20      0
May     132   NaN    52     90
Jun     205  60.0    55    100

In [53]:
other = pd.DataFrame({'eggs': ['K0', 'K1', 'K2'],
                      'salt': ['b10', 'b20', 'b50'],
                      'spam': ['s1', 's2', 's3'],
                      'bacon': ['bc0', 'bc1', 'cb2']},index=["July", "Aug", "Sept"])
other

     eggs salt spam bacon
July   K0  b10   s1   bc0
Aug    K1  b20   s2   bc1
Sept   K2  b50   s3   cb2

In [54]:
df2.append(other)

     eggs  salt spam bacon
Jan    47  12.0   17     0
Feb   110  50.0   31     0
Mar   221  89.0   72    60
Apr    77  87.0   20     0
May   132   NaN   52    90
Jun   205  60.0   55   100
July   K0   b10   s1   bc0
Aug    K1   b20   s2   bc1
Sept   K2   b50   s3   cb2

In [55]:
df3

       eggs  salt  spam  bacon
month
Jan      47  12.0    17      0
Feb     110  50.0    31      0
Mar     221  89.0    72     60
Apr      77  87.0    20      0
May     132   NaN    52     90
Jun     205  60.0    55    100

In [56]:
df3.columns=['X', 'Y', 'Z','T']
df3

         X     Y   Z    T
month
Jan     47  12.0  17    0
Feb    110  50.0  31    0
Mar    221  89.0  72   60
Apr     77  87.0  20    0
May    132   NaN  52   90
Jun    205  60.0  55  100

In [57]:
df3.drop("T",axis=1,inplace=True)
df3

         X     Y   Z
month
Jan     47  12.0  17
Feb    110  50.0  31
Mar    221  89.0  72
Apr     77  87.0  20
May    132   NaN  52
Jun    205  60.0  55

#DataFrames with zeros and NaNs

Select columns with all nonzeros

In [58]:
df

       eggs  salt  spam
month
Jan      47  12.0    17
Feb     110  50.0    31
Mar     221  89.0    72
Apr      77  87.0    20
May     132   NaN    52
Jun     205  60.0    55

In [59]:
df['bacon']=[0,0,0,0,0,1]
df['bacon'].any()

True

In [60]:
df

       eggs  salt  spam  bacon
month
Jan      47  12.0    17      0
Feb     110  50.0    31      0
Mar     221  89.0    72      0
Apr      77  87.0    20      0
May     132   NaN    52      0
Jun     205  60.0    55      1

In [61]:
df.loc[:, df.all()]

       eggs  salt  spam
month
Jan      47  12.0    17
Feb     110  50.0    31
Mar     221  89.0    72
Apr      77  87.0    20
May     132   NaN    52
Jun     205  60.0    55

Select columns with any NaNs

In [62]:
df.loc[:, df.isnull().any()]

       salt
month
Jan    12.0
Feb    50.0
Mar    89.0
Apr    87.0
May     NaN
Jun    60.0

Select columns without NaNs

In [63]:
df

       eggs  salt  spam  bacon
month
Jan      47  12.0    17      0
Feb     110  50.0    31      0
Mar     221  89.0    72      0
Apr      77  87.0    20      0
May     132   NaN    52      0
Jun     205  60.0    55      1

In [64]:
df.loc[:, df.notnull().any()]

       eggs  salt  spam  bacon
month
Jan      47  12.0    17      0
Feb     110  50.0    31      0
Mar     221  89.0    72      0
Apr      77  87.0    20      0
May     132   NaN    52      0
Jun     205  60.0    55      1

Drop rows with any NaNs

In [65]:
df.dropna(how='any')

       eggs  salt  spam  bacon
month
Jan      47  12.0    17      0
Feb     110  50.0    31      0
Mar     221  89.0    72      0
Apr      77  87.0    20      0
Jun     205  60.0    55      1

In [66]:
df

       eggs  salt  spam  bacon
month
Jan      47  12.0    17      0
Feb     110  50.0    31      0
Mar     221  89.0    72      0
Apr      77  87.0    20      0
May     132   NaN    52      0
Jun     205  60.0    55      1

In [67]:
df.salt > 55

month
Jan    False
Feb    False
Mar     True
Apr     True
May    False
Jun     True
Name: salt, dtype: bool

Filtering a column based on another

In [68]:
df.eggs[df.salt > 55]  #returns a series

month
Mar    221
Apr     77
Jun    205
Name: eggs, dtype: int64